### ISSUE TITLE
code analysis crash: Error: Cannot use object of type Drupal\Core\Plugin\Context\ContextDefinition as array in Drupal\Component\Annotation\Plugin->setClass

### ISSUE THREAD

**Issue by joachim-n** [drupal-code-builder/drupal-code-builder#166]
```
Error: Cannot use object of type Drupal\Core\Plugin\Context\ContextDefinition as array in Drupal\Component\Annotation\Plugin->setClass() (line 109 of /var/www/docroot/core/lib/Drupal/Component/Annotation/Plugin.php) 
#0 /var/www/docroot/core/lib/Drupal/Component/Annotation/Plugin/Discovery/AnnotatedClassDiscovery.php(179): Drupal\Component\Annotation\Plugin->setClass('Drupal\\language...') 
#1 /var/www/docroot/core/lib/Drupal/Core/Plugin/Discovery/AnnotatedClassDiscovery.php(85): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->prepareAnnotationDefinition(Object(Drupal\Core\Annotation\ContextDefinition), 'Drupal\\language...') 
#2 /var/www/docroot/core/lib/Drupal/Component/Annotation/Plugin/Discovery/AnnotatedClassDiscovery.php(146): Drupal\Core\Plugin\Discovery\AnnotatedClassDiscovery->prepareAnnotationDefinition(Object(Drupal\Core\Annotation\ContextDefinition), 'Drupal\\language...') 
#3 /var/www/docroot/core/lib/Drupal/Component/Plugin/Discovery/DerivativeDiscoveryDecorator.php(86): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->getDefinitions() 
#4 /var/www/docroot/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(284): Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions() 
#5 /var/www/docroot/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(175): Drupal\Core\Plugin\DefaultPluginManager->findDefinitions() 
#6 /var/www/vendor/drupal-code-builder/drupal-code-builder/Task/Collect/PluginTypesCollector.php(601): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() 
#7 /var/www/vendor/drupal-code-builder/drupal-code-builder/Task/Collect/PluginTypesCollector.php(577): DrupalCodeBuilder\Task\Collect\PluginTypesCollector->analysePluginTypeBaseClass(Array) 
#8 /var/www/vendor/drupal-code-builder/drupal-code-builder/Task/Collect/PluginTypesCollector.php(293): DrupalCodeBuilder\Task\Collect\PluginTypesCollector->addPluginBaseClass(Array) 
#9 /var/www/vendor/drupal-code-builder/drupal-code-builder/Task/Collect/PluginTypesCollector.php(124): DrupalCodeBuilder\Task\Collect\PluginTypesCollector->gatherPluginTypeInfo(Array) 
#10 /var/www/vendor/drupal-code-builder/drupal-code-builder/Task/Collect.php(121): DrupalCodeBuilder\Task\Collect\PluginTypesCollector->collect(Array) 
#11 /var/www/docroot/modules/contrib/module_builder/src/Form/ProcessForm.php(157): DrupalCodeBuilder\Task\Collect->collectComponentDataIncremental(Array, Array) 
#12 /var/www/docroot/core/includes/batch.inc(295): Drupal\module_builder\Form\ProcessForm::batchOperation(Array, Array) 
#13 /var/www/docroot/core/includes/batch.inc(137): _batch_process() 
#14 /var/www/docroot/core/includes/batch.inc(93): _batch_do() 
#15 /var/www/docroot/core/modules/system/src/Controller/BatchController.php(55): _batch_page(Object(Symfony\Component\HttpFoundation\Request)) 
#16 [internal function]: Drupal\system\Controller\BatchController->batchPage(Object(Symfony\Component\HttpFoundation\Request)) 
#17 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) 
#18 /var/www/docroot/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() 
#19 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) 
#20 /var/www/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) 
#21 /var/www/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() 
#22 /var/www/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#23 /var/www/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#24 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#25 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#26 /var/www/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#27 /var/www/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#28 /var/www/docroot/core/modules/ban/src/BanMiddleware.php(50): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#29 /var/www/docroot/modules/contrib/shield/src/ShieldMiddleware.php(166): Drupal\ban\BanMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#30 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#31 /var/www/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#32 /var/www/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#33 /var/www/docroot/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#34 /var/www/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#35 {main}.
```

**Comment by joachim-n** [comment]
Problem was https://www.drupal.org/project/config_inspector/issues/3089626

**Comment by joachim-n** [comment]
WIP on branch `sandbox-166`.
